### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by soidisant** [jenspfahl/KeepAwake#12]
Small issue, if ~/.local/share/gnome-shell/extensions/ does not exist before you issue the command
cp -r KeepAwake/KeepAwake@jepfa.de ~/.local/share/gnome-shell/extensions/ 
Then the contents of the folder KeepAwake@jepfa.de get copied into extensions, not the folder itself. Therefore the extensions cannot be found by tweaks. 

Great work otherwise!

**Comment by dreua** [comment]
Oh well, that's my bad, sorry. Hopefully I will have time on the weekend to come up with more bullet-proof instructions.
Thanks for reporting!
