### ISSUE TITLE
Tray icons

### ISSUE THREAD

**Issue by thanosgatos** [jenspfahl/KeepAwake#15]
Is there any way to get rid of the yellow-ish square around the tray icon? Even use a different icon in general maybe?

**Comment by dreua** [comment]
Of course, just delete these lines: https://github.com/jenspfahl/KeepAwake/blob/3577eb3990fe774c115f226cd8fc1057253f4570/KeepAwake%40jepfa.de/extension.js#L258-L263

For the icons: Just replace the files in the icons directory. (You need to have the new icons in SVG-format or else you have to change more, shouldn't bee too hard though.)

You will have to restart the Gnome Shell for these changes to have effect. (See Readme on how to do that.)

Also keep in mind that any updates might overwrite these changes back to the default and I'm not sure if @jenspfahl  wants to implement any of this in his main extension. I like the way it currently works and looks but if you have a suggestion for a better icon just post it here.

**Comment by thanosgatos** [comment]
Thanks for the quick reply! 

I did some digging of my own and I figured it out--it wasn't that hard after all. Instead of removing the lines you mentioned, I changed all values to 0. It took some time and quite a few reboots, but it worked.

About the icons, should the new icons be named exactly the same as the old ones? I would guess so, but asking just in case.

**Comment by dreua** [comment]
You don't have to reboot, restarting Gnome should be enough (Alt+F2, r if you use Xorg, that's quite fast. On Wayland you have to logout, login. You can select to use Xorg or Wayland on each login by the small tooth-wheel beneath your password field.)

If you have the new icons in SVG-format it would be easiest to just replace them and name them exactly the same. (I would copy/paste the filenames from the original icons to be safe.)

**Comment by thanosgatos** [comment]
Thanks a ton! For now, I'm using the caffeine icons, because they make it easier for me to understand whether it is on or not. I am closing this issue. Thank you for the help once again.
