### ISSUE TITLE
Extenstion stops working while screen is locked

### ISSUE THREAD

**Issue by yura-pakhuchiy** [jenspfahl/KeepAwake#21]
Works perfectly if I do not lock screen, however stops working if screen is locked. It would be great if it will continue work with locked screen in 3rd mode (keep awake even after restarts).

**Comment by jenspfahl** [comment]
Just tested this and I discovered another behavior. When it is in 2nd state (keep awake) it doesn't recover the state. For the 3rd state, it works fine.

**Comment by yura-pakhuchiy** [comment]
Just to clarify, my issue is that extension does not work while screen is locked. Eg., I would like to leave laptop to download some large file or to compile something big, but lock the screen at the same time, so I can leave the computer unattended.

**Comment by tschai-yim** [comment]
This still seems to be the case, which is really unfortunate. Most of my use-cases also involve leaving the computer unattended to process / download something. Would it be possible to not undo the changes in [`disable()`](https://github.com/jenspfahl/KeepAwake/blob/master/KeepAwake%40jepfa.de/extension.js#L450) when the locked mode is enabled, because this method also gets called when the screen gets locked (as documented [here](https://gjs.guide/extensions/overview/anatomy.html#extension-js-required))?

**Comment by jenspfahl** [comment]
Yes, instead of resetting the values to default I could just keep them. Maybe I will add a new settings option to opt-in to this behavior to not break current expectations.

**Comment by tschai-yim** [comment]
Thanks for the extension and taking the time to address this. It might then also make sense to allow for screen dimming (#25) while in locked mode or the very least while the screen is locked (by still resetting it to the default).

btw. it seems the extension currently doesn't reset the setting changes when being disabled but sets them to the factory defaults, which for some users (not in my case though) might cause unintended side effects.

**Comment by yura-pakhuchiy** [comment]
@tschai-yim If you are using systemd, `systemd-inhibit cat` in a terminal provides the behavior we want. Then just press Ctrl-D 2 times to cancel and close the terminal.

**Comment by tschai-yim** [comment]
> @tschai-yim If you are using systemd, `systemd-inhibit cat` in a terminal provides the behavior we want. Then just press Ctrl-D 2 times to cancel and close the terminal.

Hmm, tried it out yesterday and didn't seem to work. My laptop still suspended (or at least looked like that, given the progress of the running process), though I haven't checked it out in detail yet. But in any case, I think the feature request still stands as a togglable indicator in the menu bar is a lot nicer than having to type in a command in another window.

**Comment by jenspfahl** [comment]
Added to the recent version (published on EGO)

**Comment by Jet132** [comment]
@jenspfahl Thanks a thousand! Just tested it and the updates fix all my pain points completely! :ok_hand:

**Comment by tschai-yim** [comment]
@jenspfahl Thanks a thousand! Just tested it and the updates fix all my pain points completely! 👌
