### ISSUE TITLE
Support for Kinetic/Gnome Shell 43

### ISSUE THREAD

**Issue by MatzFan** [jenspfahl/KeepAwake#35]
Just upgraded to Kinetic Kudu and noticed that the extension is incompatible with gnome-shell 43.

**Comment by jenspfahl** [comment]
Thanks for noticing me. I am still with Gnome 42 so i didn't know. I will fix this when I can reproduce.

**Comment by RubenKelevra** [comment]
@jenspfahl it is marked as incompatible on extensions.gnome.org but in my limited testing it works fine with 43.1.

**Comment by jenspfahl** [comment]
Yes, it seems to work with Gnome 43. Currently it is not configured for the new Gnome version. I gonna add this version.
