### ISSUE TITLE
Support for GNOME 44.

### ISSUE THREAD

**Issue by kanannuruyevs** [jenspfahl/KeepAwake#36]
Hi there. The extension's great, but please update it for the new version of GNOME. Thanks.

**Comment by tadas-s** [comment]
@kanansnote you can disable version check to install it:

![Screenshot from 2023-04-21 21-10-21](https://user-images.githubusercontent.com/840454/233726738-b9efc283-4c78-4f82-a943-2471acc58230.png)

I've just tested it and seems to work fine on Fedora 38 with Gnome 44.

**Comment by kanannuruyevs** [comment]
@tadas-s I think that wouldn't be possible for me, as I assume having an account on the website is a must to access those settings.

**Comment by tadas-s** [comment]
If you visit the extensions website https://extensions.gnome.org/ it will suggest to install Gnome Extensions browser addon. With that addon that website becomes like an app for managing your installed extensions.. No need for any kind of account (I know, it's weird..).

**Comment by jenspfahl** [comment]
I have merged and uploaded the recent pull requests from @tadas-s to extensions.gnome.org, thanks for that! Let's wait to get the upload verified by Gnome.

**Comment by kanannuruyevs** [comment]
Thank you both. It works now.
