### ISSUE TITLE
[Suggestion] Distinguish between system and display sleep

### ISSUE THREAD

**Issue by BuzzKnightbeer** [jenspfahl/KeepAwake#43]
So that the system stays awake but the display can turn off.
Similar to how the Micrisft Powertoys extension works:
![image](https://github.com/jenspfahl/KeepAwake/assets/45749699/65486220-3796-412e-a492-94d5a51c6b01)

**Comment by jenspfahl** [comment]
Added to the recent version (published on EGO)
