### ISSUE TITLE
Ability to disable suspend in one click, but also enable screensaver

### ISSUE THREAD

**Issue by drivera73** [jenspfahl/KeepAwake#6]
In some use cases, one wishes to leave the computer on a long-running process, but need to lock the screens so the computer is inaccessible to others while doing so.

I've found that using this tool is missing that bit of functionality: allow the lock/screensaver to kick in to protect the console while simultaneously disabling suspend.

Currently I handle this directly in the power management dialog, but this would be a nice feature to have.

**Comment by jenspfahl** [comment]
Could be a nice feature that can be enabled within a config dialog. But it is very special and not the goal of this simple extension. You could checkout Caffeine if they have this function.
