### ISSUE TITLE
automatic

### ISSUE THREAD

**Issue by JediBrooker** [jenspfahl/KeepAwake#7]
could you perhaps make it so that it automatically detects a fullscreen video (html5/flash/vlc, etc) and inhibits power management while the video is playing and then turn back on power management once the video has finished?

**Comment by jenspfahl** [comment]
This is just a small extension without any blowed up functions. But you can use https://extensions.gnome.org/extension/517/caffeine/ instead. This supports inhibit auto suspend etc.
