### ISSUE TITLE
Feature request: restore state

### ISSUE THREAD

**Issue by cyberalex4life** [jenspfahl/KeepAwake#8]
Hi there, could you implement active/inactive state restore? For the time being I added
`toggleMode();`
to function enable(). It can be a very simple thing, like a text file. Thank you for your effort anyway.

**Comment by jenspfahl** [comment]
The idea was to let your computer keep awake for just a temporary time. Therefore I didn't restore the last toggle state. But it would be a nice thing to have this restore option. Maybe someone can implement this. So we need to have a config dialog for this extension.

**Comment by neffo** [comment]
What about a 3rd state for the toggle? Saves the need to implement preferences, although would need to implement dconf settings & schema.

On, On (Locked), Off

**Comment by cyberalex4life** [comment]
It's ok if it does the job.
